version: '2'

services:

  nebula-rest-api:
    image: elestio/nebula-rest-api
    container_name: nebula-rest-api
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stop_grace_period: 1s
    ports:
      - "4242:4242/udp"
      - "127.0.0.1:9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nebula/config:/usr/src/app/nebula/config
      